### ISSUE TITLE
Ctrl + F only searches visible paragraphs

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/Lexoral#40]
Due to the conditional rendering of components, it can't see the sections that are currently off-screen. We'll need to replace the browser's search with something custom, like google drive does.

**Comment by Valjean42** [comment]
Seems to work for me, using Opera browser.

**Comment by stevenwaterman** [comment]
You're right, conditional rendering was removed ages ago https://github.com/stevenwaterman/Lexoral/commit/e889621ad6539b4e527a2f5c4e879b593faf79ff
