### ISSUE TITLE
Sections desync with audio sometimes

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/Lexoral#50]
I think this is due to the aligner function - If two alternatives each contain a different number of words, then we have to assign the section timings based on the timings for the first option. This should be possible to fix for future transcripts by updating the aligner function

**Comment by Valjean42** [comment]
It seems this is no longer a problem. You probably fixed this long ago but I just made sure, even when there's multiple-word alternatives there is no desync

**Comment by stevenwaterman** [comment]
Cool, thank you. I assumed that would be the case - I'll close this for now!
