### ISSUE TITLE
When clicking an option in the dropdown it doesn't always disappear

### ISSUE THREAD

**Issue by ermagherdchips** [stevenwaterman/Lexoral#64]

**Comment by stevenwaterman** [comment]
Dropdown has no concept of complete / incomplete, only disappears when there is only 1 option left. If there are two options where one is a subset of another, ie:

- Hi
- Hiya

Then accepting the first option will not remove the dropdown as both options are still possible given the current text in the section (`hi`)

To solve this, we need to add a new piece of state on each section, `confirmed`. This is true if a dropdown option has been picked for that section. If it is true, the dropdown will never appear for that section.
