### ISSUE TITLE
404 on you-dont-need-js style sheets

### ISSUE THREAD

**Issue by HookedBehemoth** [stevenwaterman/Lexoral#73]
I get 404s on [this](https://lexoral.com/blog/you-dont-need-js/) pages style sheets, breaking pretty much all showcases.

![image](https://user-images.githubusercontent.com/22580720/156182312-354fa4ba-5601-4089-8158-f63a39ad0233.png)

**Comment by stevenwaterman** [comment]
It's working for me, so it's not that the URLs are invalid or anything like that. Are you able to access the stylesheets directly? I've also been having some issues with my CI pipeline in the last hour or so, meaning it may just be that GitHub is struggling at the minute

**Comment by HookedBehemoth** [comment]
Refreshing the entire page fixed it now on all my devices.
